name: Run tests on Push 

on:
  push:
    branches:    
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -t selenium_test_run . 
      
    - name: Run the Docker container
      run: docker run selenium_test_run
